theme: jekyll-theme-dinky
title: Pareidolia
description: sometimes bananas have bruises in the form of a face, or perhaps are rearranged to look like faces. Sometimes they even look like a face by themselves! This page gives a couple examples.
